apiVersion: v1
kind: Service
metadata:
  name: fjordline-booking-service
spec:
  selector:
    app: fjordline-booking
  ports:
    - protocol: TCP
      port: 80       # Porten utad
      targetPort: 8080 # Porten inne i containeren
  type: LoadBalancer # Gjør appen tilgjengelig fra internett